# config.yml

# Data Configuration
data:
  train_dir: /path/to/training_data
  validation_dir: /path/to/validation_data
  test_dir: /path/to/test_data
  image_size: (224, 224)  # Size to which images will be resized
  normalization: true    # Apply image normalization

# Model Configuration
model:
  architecture: CNN
  learning_rate: 0.001
  batch_size: 32
  epochs: 20

# Data Augmentation
augmentation:
  enabled: true
  rotation_range: 20
  width_shift_range: 0.2
  height_shift_range: 0.2
  horizontal_flip: true
  vertical_flip: false

# Training Metrics
metrics:
  - accuracy
  - precision
  - recall
  - f1_score

# Logging and Saving
logging:
  log_dir: /path/to/logs
  checkpoint_dir: /path/to/checkpoints
  experiment_name: my_image_classification_experiment